# Generated by Django 4.2 on 2024-03-14 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about_us_images', verbose_name='Сменить изображение')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='educational_images', verbose_name='Сменить изображение')),
            ],
            options={
                'verbose_name': 'Обучение',
                'verbose_name_plural': 'Обучение',
            },
        ),
        migrations.CreateModel(
            name='all_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images', verbose_name='Сменить изображение')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Все новости',
                'verbose_name_plural': 'Все новости',
            },
        ),
        migrations.CreateModel(
            name='all_programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата')),
                ('price', models.TextField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Все программы',
                'verbose_name_plural': 'Все программы',
            },
        ),
        migrations.CreateModel(
            name='FilterArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.TextField(verbose_name='Фильтр')),
            ],
            options={
                'verbose_name': 'Фильтры статей',
                'verbose_name_plural': 'Фильтры статей',
            },
        ),
        migrations.CreateModel(
            name='Otrasl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OtraslNauki', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('image', models.ImageField(upload_to='person_images', verbose_name='Сменить изображение')),
                ('name', models.TextField(verbose_name='Имя')),
                ('field_activity', models.TextField(verbose_name='Сфера научной деятельности')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('experience', models.TextField(verbose_name='Стаж работы')),
                ('professional_experience', models.TextField(verbose_name='Профессиональный опыт')),
                ('education', models.TextField(verbose_name='Образование')),
                ('dop_education', models.TextField(verbose_name='Дополнительное образование')),
                ('students_disciplined', models.TextField(verbose_name='Преподаваемые дисциплины и курсы')),
                ('membership_editorial_boards', models.TextField(verbose_name='Членство в редколлегиях')),
                ('publications_appearances', models.TextField(verbose_name='Публикации и выступления в СМИ')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.CreateModel(
            name='program_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('profession', models.CharField(max_length=128, verbose_name='Профессия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='profession_images', verbose_name='Сменить изображение')),
            ],
            options={
                'verbose_name': 'Преподаватели',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author', models.CharField(max_length=64, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('name', models.TextField(verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Сервисы',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='service_faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сервисы FAQ',
                'verbose_name_plural': 'Сервисы FAQ',
            },
        ),
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teg', models.TextField(verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Теги кейсов',
                'verbose_name_plural': 'Теги кейсов',
            },
        ),
        migrations.CreateModel(
            name='tip_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField(verbose_name='Тип статьи')),
            ],
            options={
                'verbose_name': 'Тип статьи',
                'verbose_name_plural': 'Тип статьи',
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cases_image', verbose_name='Сменить изображение')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('teg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teg')),
            ],
            options={
                'verbose_name': 'Кейсы',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='articles_inner',
            fields=[
                ('articles_name', models.CharField(max_length=128, verbose_name='Название статьи')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата статьи')),
                ('image', models.ImageField(upload_to='articles_images', verbose_name='Сменить изображение')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('group_specialties', models.TextField(verbose_name='Группа специальностей')),
                ('status', models.TextField(verbose_name='Статус')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('teg', models.TextField(verbose_name='Тег статьи')),
                ('branch_science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.otrasl')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.filterarticle')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tip_news')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
