# Generated by Django 4.2 on 2024-03-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
            options={
                'verbose_name': 'Статус для Статей',
                'verbose_name_plural': 'Статус для Статей',
            },
        ),
        migrations.AlterModelOptions(
            name='otrasl',
            options={'verbose_name': 'Отрасль науки Статьи', 'verbose_name_plural': 'Отрасль науки Статьи'},
        ),
        migrations.AlterField(
            model_name='articles_inner',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.statusarticle'),
        ),
    ]
