# Generated by Django 4.2 on 2024-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_statusarticle_alter_otrasl_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupSpec', models.TextField()),
            ],
            options={
                'verbose_name': 'Группа специальностей для статей',
                'verbose_name_plural': 'Группа специальностей для статей',
            },
        ),
        migrations.RenameField(
            model_name='statusarticle',
            old_name='status',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='articles_inner',
            name='group_specialties',
        ),
        migrations.AddField(
            model_name='articles_inner',
            name='group_specialties',
            field=models.ManyToManyField(to='mainapp.groupspec'),
        ),
    ]
