# Generated by Django 4.2 on 2024-03-14 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_groupspec_rename_status_statusarticle_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document', models.TextField()),
            ],
            options={
                'verbose_name': 'Документ Программы',
                'verbose_name_plural': 'Документ Программы',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormatProgramm', models.TextField()),
            ],
            options={
                'verbose_name': 'Формат обучение Программы',
                'verbose_name_plural': 'Формат обучение Программы',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название программы')),
                ('price', models.IntegerField(verbose_name='Цена программы')),
                ('start', models.TextField(verbose_name='Старт курса')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата курса')),
                ('prod', models.TextField(verbose_name='Продолжительность программы')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.document')),
                ('formats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.format')),
            ],
            options={
                'verbose_name': 'Программы',
                'verbose_name_plural': 'Программы',
            },
        ),
    ]
