# Generated by Django 4.2 on 2024-03-14 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_document_format_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='start',
        ),
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата старта курса'),
        ),
    ]
