# Generated by Django 4.2 on 2024-03-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_program_start_alter_program_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='rejim',
            field=models.TextField(default=1, verbose_name='Режим занятий'),
            preserve_default=False,
        ),
    ]
