# Generated by Django 4.2 on 2024-03-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_program_rejim'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание программы'),
            preserve_default=False,
        ),
    ]
