# Generated by Django 4.2 on 2024-03-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_program_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='all_programs',
        ),
    ]
