# Generated by Django 4.2 on 2024-03-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_delete_all_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners_image', verbose_name='Сменить изображение')),
                ('name', models.TextField(verbose_name='Имя ')),
            ],
        ),
        migrations.DeleteModel(
            name='all_news',
        ),
    ]
