# Generated by Django 4.2 on 2024-03-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_partners_delete_all_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Партнёры', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AddField(
            model_name='program',
            name='hours_program',
            field=models.TextField(default=1, verbose_name='Часы программы обучения'),
            preserve_default=False,
        ),
    ]
