# Generated by Django 4.2 on 2024-03-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_partners_options_program_hours_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_description1',
            field=models.TextField(default=1, verbose_name='Программа обучение описание 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='program_description2',
            field=models.TextField(default=1, verbose_name='Программа обучение описание 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='program_description3',
            field=models.TextField(default=1, verbose_name='Программа обучение описание 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='program_description4',
            field=models.TextField(default=1, verbose_name='Программа обучение описание 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='program_description5',
            field=models.TextField(default=1, verbose_name='Программа обучение описание 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='program_description6',
            field=models.TextField(default=1, verbose_name='Программа обучение описание 6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='program_description7',
            field=models.TextField(default=1, verbose_name='Программа обучение описание 7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='program_description8',
            field=models.TextField(default=1, verbose_name='Программа обучение описание 8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='program_description9',
            field=models.TextField(default=1, verbose_name='Программа обучение описание 9'),
            preserve_default=False,
        ),
    ]
