# Generated by Django 4.2 on 2024-03-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_program_program_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='obuch',
            field=models.TextField(default=1, verbose_name='Кому подойдет обучение название 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='obuch1',
            field=models.TextField(default=1, verbose_name='Кому подойдет обучение название 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='obuch2',
            field=models.TextField(default=1, verbose_name='Кому подойдет обучение описание 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='obuch3',
            field=models.TextField(default=1, verbose_name='Кому подойдет обучение описание 3'),
            preserve_default=False,
        ),
    ]
