# Generated by Django 4.2 on 2024-03-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_program_obuch_program_obuch1_program_obuch2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='obuch',
        ),
        migrations.AddField(
            model_name='program',
            name='obuch4',
            field=models.TextField(default=1, verbose_name='Кому подойдет обучение описание 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='obuch5',
            field=models.TextField(default=1, verbose_name='Кому подойдет обучение название 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='obuch6',
            field=models.TextField(default=1, verbose_name='Кому подойдет обучение описание 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='obuch1',
            field=models.TextField(verbose_name='Кому подойдет обучение название 1'),
        ),
        migrations.AlterField(
            model_name='program',
            name='obuch2',
            field=models.TextField(verbose_name='Кому подойдет обучение описание 1'),
        ),
        migrations.AlterField(
            model_name='program',
            name='obuch3',
            field=models.TextField(verbose_name='Кому подойдет обучение название 2'),
        ),
    ]
