# Generated by Django 4.2 on 2024-03-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_program_obuch_program_obuch4_program_obuch5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='srok',
            field=models.TextField(default=1, verbose_name='Срок обучение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='vhod',
            field=models.TextField(default=1, verbose_name='В стоймость входит'),
            preserve_default=False,
        ),
    ]
