# Generated by Django 4.2 on 2024-03-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_program_srok_program_vhod'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='desc',
            field=models.TextField(default=1, verbose_name='Стоймость обучение описание'),
            preserve_default=False,
        ),
    ]
