# Generated by Django 4.2 on 2024-03-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_program_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='rasroch',
            field=models.TextField(default=1, verbose_name='Рассрочка'),
            preserve_default=False,
        ),
    ]
