# Generated by Django 4.2 on 2024-03-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_program_rasroch'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='ot',
            field=models.IntegerField(default=1, verbose_name='От рублей по рассрочке'),
            preserve_default=False,
        ),
    ]
