# Generated by Django 4.2 on 2024-03-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_program_ot'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='skidka_do',
            field=models.TextField(default=1, verbose_name='Скидка до'),
            preserve_default=False,
        ),
    ]
