# Generated by Django 4.2 on 2024-03-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_program_skidka_do'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='teg',
        ),
        migrations.AddField(
            model_name='cases',
            name='teg',
            field=models.ManyToManyField(to='mainapp.teg'),
        ),
    ]
