# Generated by Django 4.2 on 2024-03-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_remove_cases_teg_cases_teg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='teg',
        ),
        migrations.AddField(
            model_name='cases',
            name='teg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.teg'),
            preserve_default=False,
        ),
    ]
