# Generated by Django 4.2 on 2024-03-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_remove_cases_teg_cases_teg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='teg',
        ),
        migrations.AddField(
            model_name='cases',
            name='teg',
            field=models.ManyToManyField(to='mainapp.teg'),
        ),
    ]
