# Generated by Django 4.2 on 2024-03-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_remove_cases_teg_cases_teg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='video',
            field=models.TextField(default=1, verbose_name='Ссылка на видео'),
            preserve_default=False,
        ),
    ]
