# Generated by Django 4.2 on 2024-04-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_alter_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость программы'),
        ),
    ]
