# Generated by Django 4.2 on 2024-04-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_alter_program_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='prod',
            field=models.IntegerField(verbose_name='Продолжительность программы'),
        ),
    ]
