# Generated by Django 4.2 on 2024-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_alter_program_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='prod_mes',
            field=models.CharField(default=1, max_length=128, verbose_name='Продолжительность программы в месяцах'),
            preserve_default=False,
        ),
    ]
