# Generated by Django 4.2 on 2024-04-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_program_prod_mes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документ'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'verbose_name': 'Формат обучение', 'verbose_name_plural': 'Формат обучение'},
        ),
        migrations.AlterField(
            model_name='program',
            name='rejim',
            field=models.CharField(max_length=128, verbose_name='Режим занятий'),
        ),
    ]
