# Generated by Django 4.2 on 2024-04-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_alter_document_options_alter_format_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='zagolovok',
            field=models.CharField(default=1, max_length=128, verbose_name='Заголовок - продолжение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='zagolovok_kras',
            field=models.CharField(default=1, max_length=128, verbose_name='Заголовок красным'),
            preserve_default=False,
        ),
    ]
