# Generated by Django 4.2 on 2024-04-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_program_zagolovok_program_zagolovok_kras'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='pred_nav',
            field=models.TextField(default=1, verbose_name='Приобретаемый навык'),
            preserve_default=False,
        ),
    ]
