# Generated by Django 4.2 on 2024-04-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_program_pred_nav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='hours_program',
        ),
    ]
