# Generated by Django 4.2 on 2024-04-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_remove_program_hours_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='srok',
        ),
    ]
