# Generated by Django 4.2 on 2024-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_remove_program_srok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='sale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер скидки (%)'),
        ),
    ]
