# Generated by Django 4.2 on 2024-04-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_alter_program_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='rasroch',
            field=models.BooleanField(verbose_name='Рассрочка'),
        ),
    ]
