# Generated by Django 4.2 on 2024-04-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_alter_program_rasroch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='ot',
            field=models.IntegerField(verbose_name='Сумма рассрочки в месяц'),
        ),
    ]
