# Generated by Django 4.2 on 2024-04-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_alter_program_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='skidka_do',
            field=models.DateField(verbose_name='Дата завершения акции'),
        ),
    ]
