# Generated by Django 4.2 on 2024-04-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_alter_program_skidka_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='rasroch_mes',
            field=models.TextField(default=1, verbose_name='В месяц по рассрочке'),
            preserve_default=False,
        ),
    ]
