# Generated by Django 4.2 on 2024-04-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_program_rasroch_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_description2',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_description3',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_description4',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_description5',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_description6',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_description7',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_description8',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_description9',
        ),
        migrations.AlterField(
            model_name='program',
            name='program_description1',
            field=models.TextField(verbose_name='Содержание программы'),
        ),
    ]
