# Generated by Django 4.2 on 2024-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_remove_program_program_description2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_sod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sod', models.TextField()),
            ],
            options={
                'verbose_name': 'Содержание программы',
                'verbose_name_plural': 'Содержание программы',
            },
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_description1',
        ),
        migrations.AddField(
            model_name='program',
            name='program_soderj',
            field=models.ManyToManyField(to='mainapp.program_sod'),
        ),
    ]
