# Generated by Django 4.2 on 2024-04-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_program_sod_remove_program_program_description1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='obuch1',
        ),
        migrations.RemoveField(
            model_name='program',
            name='obuch2',
        ),
        migrations.RemoveField(
            model_name='program',
            name='obuch3',
        ),
        migrations.RemoveField(
            model_name='program',
            name='obuch4',
        ),
        migrations.RemoveField(
            model_name='program',
            name='obuch5',
        ),
        migrations.RemoveField(
            model_name='program',
            name='obuch6',
        ),
        migrations.AddField(
            model_name='program',
            name='obuch',
            field=models.TextField(default=1, verbose_name='Кому подойдет обучение'),
            preserve_default=False,
        ),
    ]
