# Generated by Django 4.2 on 2024-04-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_obuch_alter_program_sod_sod'),
    ]

    operations = [
        migrations.AddField(
            model_name='obuch',
            name='opis',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obuch',
            name='obuch',
            field=models.TextField(verbose_name='Заголовок'),
        ),
    ]
