# Generated by Django 4.2 on 2024-04-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_remove_program_obuch_program_komu_obuch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obuch_Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obuch_desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Кому подойдет обучение Описание',
                'verbose_name_plural': 'Кому подойдет обучение Описание',
            },
        ),
        migrations.AlterModelOptions(
            name='obuch',
            options={'verbose_name': 'Кому подойдет обучение Заголовок', 'verbose_name_plural': 'Кому подойдет обучение Заголовок'},
        ),
        migrations.RenameField(
            model_name='program',
            old_name='komu_obuch',
            new_name='komu_obuch_zagolovok',
        ),
        migrations.RemoveField(
            model_name='obuch',
            name='opis',
        ),
        migrations.AddField(
            model_name='program',
            name='komu_obuch_description',
            field=models.ManyToManyField(to='mainapp.obuch_desc'),
        ),
    ]
