# Generated by Django 4.2 on 2024-04-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_obuch_desc_alter_obuch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='prod_mes',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Продолжительность программы в месяцах'),
        ),
    ]
