# Generated by Django 4.2 on 2024-04-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_alter_program_prod_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo_image', verbose_name='Логотипы'),
            preserve_default=False,
        ),
    ]
