# Generated by Django 4.2 on 2024-04-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_alter_program_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='logo',
            new_name='image',
        ),
    ]
