# Generated by Django 4.2 on 2024-05-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_rename_logo_program_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name_service',
            field=models.CharField(default=1, max_length=156, verbose_name='Название сервиса'),
            preserve_default=False,
        ),
    ]
