# Generated by Django 4.2 on 2024-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_service_name_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Meta_Description',
            field=models.CharField(default=1, max_length=156),
            preserve_default=False,
        ),
    ]
