# Generated by Django 4.2 on 2024-05-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_service_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Meta_Description',
            field=models.CharField(max_length=156, verbose_name='Описание (мета тег)'),
        ),
    ]
