# Generated by Django 4.2 on 2024-05-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_alter_service_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='Meta_Description',
            field=models.CharField(default=1, max_length=156, verbose_name='Описание (мета тег)'),
            preserve_default=False,
        ),
    ]
