# Generated by Django 4.2 on 2024-05-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_program_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_inner',
            name='Meta_Description',
            field=models.CharField(default=1, max_length=156, verbose_name='Описание (мета тег)'),
            preserve_default=False,
        ),
    ]
