# Generated by Django 4.2 on 2024-05-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_about_meta_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='Meta_Description',
        ),
    ]
