# Generated by Django 4.2 on 2024-05-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_remove_about_meta_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections_watches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolection', models.TextField(verbose_name='Категория (сервисы)')),
            ],
        ),
    ]
