# Generated by Django 4.2 on 2024-05-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_collections_watches'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='collections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watches_collections', to='mainapp.collections_watches', verbose_name='Коллекция'),
        ),
    ]
