# Generated by Django 4.2 on 2024-05-03 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0058_service_collections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collections_watches',
            options={'verbose_name': 'Категория (сервисы)', 'verbose_name_plural': 'Категория (сервисы)'},
        ),
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL сервиса'),
        ),
        migrations.AlterField(
            model_name='articles_inner',
            name='branch_science',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.otrasl', verbose_name='Отрасль науки'),
        ),
        migrations.AlterField(
            model_name='articles_inner',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.filterarticle', verbose_name='Фильтр'),
        ),
        migrations.AlterField(
            model_name='articles_inner',
            name='group_specialties',
            field=models.ManyToManyField(to='mainapp.groupspec', verbose_name='Группа специальностей'),
        ),
        migrations.AlterField(
            model_name='articles_inner',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.statusarticle', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='articles_inner',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tip_news', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='teg',
            field=models.ManyToManyField(to='mainapp.teg', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='groupspec',
            name='GroupSpec',
            field=models.TextField(verbose_name='Группа специальностей'),
        ),
        migrations.AlterField(
            model_name='program',
            name='komu_obuch_description',
            field=models.ManyToManyField(to='mainapp.obuch_desc', verbose_name='Кому обучение (описание)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='komu_obuch_zagolovok',
            field=models.ManyToManyField(to='mainapp.obuch', verbose_name='Кому обучение (заголовок)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_soderj',
            field=models.ManyToManyField(to='mainapp.program_sod', verbose_name='Программа (содержание)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='collections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watches_collections', to='mainapp.collections_watches', verbose_name='Категория'),
        ),
    ]
