# Generated by Django 4.2 on 2024-05-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0059_alter_collections_watches_options_service_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='url',
        ),
        migrations.AddField(
            model_name='service',
            name='service_url',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='URL сервиса'),
        ),
    ]
