# Generated by Django 4.2 on 2024-05-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0060_remove_service_url_service_service_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_url',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='URL сервиса'),
        ),
    ]
