# Generated by Django 4.2 on 2024-05-06 17:53

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0061_program_program_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_url',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name', unique=True, verbose_name='URL сервиса'),
        ),
    ]
