# Generated by Django 4.2 on 2024-05-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0062_alter_program_program_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_url',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='URL сервиса'),
        ),
    ]
