# Generated by Django 4.2 on 2024-05-08 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0063_alter_program_program_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_soderj',
        ),
        migrations.AddField(
            model_name='program',
            name='program_soderj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.program_sod', verbose_name='Программа (содержание)'),
            preserve_default=False,
        ),
    ]
