# Generated by Django 4.2 on 2024-05-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0064_remove_program_program_soderj_program_program_soderj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_soderj',
        ),
        migrations.AddField(
            model_name='program',
            name='program_soderj',
            field=models.ManyToManyField(to='mainapp.program_sod', verbose_name='Программа (содержание)'),
        ),
    ]
