# Generated by Django 4.2 on 2024-05-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0065_remove_program_program_soderj_program_program_soderj'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_url',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='URL сервиса'),
        ),
    ]
