# Generated by Django 4.2 on 2024-05-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0066_person_person_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_inner',
            name='article_url',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='URL сервиса'),
        ),
    ]
