# Generated by Django 4.2 on 2024-05-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0067_articles_inner_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=156, verbose_name='Имя'),
        ),
    ]
