# Generated by Django 4.2 on 2024-05-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0068_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='field_activity',
            field=models.TextField(blank=True, null=True, verbose_name='Сфера научной деятельности'),
        ),
    ]
