# Generated by Django 4.2 on 2024-05-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0069_alter_person_field_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='experience',
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Стаж работы'),
        ),
    ]
