# Generated by Django 4.2 on 2024-05-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0070_remove_person_experience_alter_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='professional_experience',
            field=models.TextField(blank=True, null=True, verbose_name='Профессиональный опыт'),
        ),
    ]
