# Generated by Django 4.2 on 2024-05-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0071_alter_person_professional_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dop_education',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительное образование'),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='person',
            name='membership_editorial_boards',
            field=models.TextField(blank=True, null=True, verbose_name='Членство в редколлегиях'),
        ),
        migrations.AlterField(
            model_name='person',
            name='publications_appearances',
            field=models.TextField(blank=True, null=True, verbose_name='Публикации и выступления в СМИ'),
        ),
        migrations.AlterField(
            model_name='person',
            name='students_disciplined',
            field=models.TextField(blank=True, null=True, verbose_name='Преподаваемые дисциплины и курсы'),
        ),
    ]
