# Generated by Django 4.2 on 2024-05-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0072_alter_person_dop_education_alter_person_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personteg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tegis', models.TextField(verbose_name='Тег (команда)')),
            ],
            options={
                'verbose_name': 'Теги (команда)',
                'verbose_name_plural': 'Теги (команда)',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='tegis',
            field=models.ManyToManyField(to='mainapp.personteg', verbose_name='Теги (команда)'),
        ),
    ]
