# Generated by Django 4.2 on 2024-05-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0073_personteg_person_tegis'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='koord',
            field=models.BooleanField(default=1, verbose_name='Координационный совет'),
            preserve_default=False,
        ),
    ]
