# Generated by Django 4.2 on 2024-05-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0075_alter_person_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles_inner',
            name='name',
        ),
        migrations.AlterField(
            model_name='articles_inner',
            name='articles_name',
            field=models.CharField(max_length=128, verbose_name='Заголовок новости'),
        ),
    ]
