# Generated by Django 4.2 on 2024-05-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0076_remove_articles_inner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_inner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
