# Generated by Django 4.2 on 2024-05-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0077_alter_articles_inner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_inner',
            name='description',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
    ]
