# Generated by Django 4.2 on 2024-05-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0079_teginews_remove_articles_inner_teg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_inner',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tip_news', verbose_name='Тип новости'),
        ),
    ]
