# Generated by Django 4.2 on 2024-05-12 12:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0080_alter_articles_inner_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_name', models.CharField(max_length=128, verbose_name='Заголовок новости')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата новости')),
                ('image', models.ImageField(upload_to='news_images', verbose_name='Сменить изображение')),
                ('description', models.TextField(verbose_name='Текст новости')),
                ('Meta_Description', models.CharField(max_length=156, verbose_name='Описание (мета тег)')),
                ('article_url', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='URL сервиса')),
                ('teg', models.ManyToManyField(to='mainapp.teginews', verbose_name='Теги')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tip_news', verbose_name='Тип новости')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
