# Generated by Django 4.2 on 2024-05-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0081_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='article_url',
            new_name='news_url',
        ),
    ]
