# Generated by Django 4.2 on 2024-05-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0082_rename_article_url_news_news_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Заголовок')),
                ('name_cras', models.CharField(max_length=156, verbose_name='Заголовок красным')),
                ('description', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Форма на главной',
                'verbose_name_plural': 'Форма на главной',
            },
        ),
    ]
