# Generated by Django 4.2 on 2024-05-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0083_form_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_home',
            name='description',
            field=models.TextField(verbose_name='Текст описание'),
        ),
    ]
