# Generated by Django 4.2 on 2024-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0084_alter_form_home_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='ot',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма рассрочки в месяц'),
        ),
        migrations.AlterField(
            model_name='program',
            name='rasroch_mes',
            field=models.TextField(blank=True, null=True, verbose_name='В месяц по рассрочке'),
        ),
        migrations.AlterField(
            model_name='program',
            name='skidka_do',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения акции'),
        ),
    ]
