# Generated by Django 4.2 on 2024-06-17 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0085_alter_program_ot_alter_program_rasroch_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата старта курса'),
        ),
    ]
