# Generated by Django 4.2 on 2024-06-17 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0086_alter_program_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата старта курса'),
        ),
    ]
